print(f"\nGitHub User: {username}")
        # print("-" * 40)
        # print(f"Name: {user_data.get('name', 'N/A')}")
        # print(f"Bio: {user_data.get('bio', 'N/A')}")
        # print(f"Location: {user_data.get('location', 'N/A')}")
        # print(f"Public Repos: {user_data.get('public_repos', 'N/A')}")
        # print(f"Followers: {user_data.get('followers', 'N/A')}")
        # print(f"Following: {user_data.get('following', 'N/A')}")
        # print(f"Profile URL: {user_data.get('html_url', 'N/A')}")